### ISSUE TITLE
导出包失败

### ISSUE THREAD

**Issue by EdenChow** [monetking/AutoPacking-iOS#23]
[OutPutFile_Failed.md.zip](https://github.com/stackhou/AutoPacking-iOS/files/3499690/OutPutFile_Failed.md.zip)
我错误提示内容，做了个markdown文件。
请作者看看。

**Comment by leokaka1** [comment]
同样的问题

**Comment by stackhou** [comment]
打包成功了，导出失败的，看保存信息是你的PP文件(描述文件配置不对)

Error Domain=IDEProvisioningErrorDomain Code=9 ""SachorStore.app" requires a provisioning profile." UserInfo={NSLocalizedDescription="SachorStore.app" requires a provisioning profile., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}

**Comment by wangergang** [comment]
我今天也使用这个打包测试了， 那是plist 文件中参数问题， 你手动打包， 导出来， 里面有个 ExportOptions.plist 文件 然后把里面 字典 provisioningProfiles 写入这个里面对应的 plist 文件就行了
