### ISSUE TITLE
xcode12 打包失败

### ISSUE THREAD

**Issue by onewangxun** [monetking/AutoPacking-iOS#25]
xcode11 打包 OK，但是更新到 xcode12 后打包失败，失败原因如下：
![image](https://user-images.githubusercontent.com/42690459/93727574-45cbe500-fbee-11ea-9203-277e8f7ee855.png)

**Comment by monetking** [comment]
这个报错是环境问题，请核对**Xcode**-->**Preferences**...-->**Locations**页面，**Command Line Tools** 选择合适的Command。
![WX20201013-184951](https://user-images.githubusercontent.com/473027/95851534-ee500d80-0d84-11eb-8239-6886277532fe.png)
